services:
  # PostgreSQL with logical decoding enabled
  postgres:
    # image: postgres:17.5-bullseye
    image: postgres:17
    container_name: dbz-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbz_db
      # Enable logical decoding and set max connections for replication
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - pg_data_cdc:/var/lib/postgresql/data
    networks:
      - debezium-network

  # Kafka
  # kafka:
  #   image: apache/kafka:4.1.1
  #   container_name: kafka-dbz
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_NODE_ID: 1
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
  #     # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
  #     # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093

  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

  #     # Controller settings
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  #     # Broker Settings
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  #     CLUSTER_ID: OKCbdAXzS1Sd-AoE_kCQQQ
  #   networks:
  #     - debezium-network
  #   healthcheck:
  #     test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
  #     interval: 5s
  #     retries: 20

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka-dbz
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
    - debezium-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 5s
      retries: 20


  # Kafka Connect with Debezium 
  debezium-kafka-connect:
    build: .
    # image: debezium/connect:2.7.3.Final
    image: debezium-kafka-connect
    container_name: debezium-kafka-connect
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: cdc_connect-group
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses 
      # Set up internal topics with appropriate settings
      # CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      # CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      # Schema Registry Integration:
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter #### add when add avro schema registry
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter #### add when add avro schema registry
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081 #### add when add avro schema registry
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081 #### add when add avro schema registry

      # REST
      CONNECT_REST_ADVERTISED_HOST_NAME: connect

      # Plugins
      # CONNECT_PLUGIN_PATH: /kafka/connect

    volumes:
      - debezium_plugins:/kafka/connect/plugins
      - debezium_data:/kafka/data
    networks:
      - debezium-network

  # Elasticsearch 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - debezium-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_DEBUG: "true"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"
    networks:
      - debezium-network


# kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "18000:8080"
    environment:
    
      # Kafka Cluster Configuration
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium-kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-kafka-connect:8083
    volumes:
      - ./config:/etc/kafka/config
      - kafka-ui-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - kafka
      - schema-registry
      - debezium-kafka-connect
    # Resource limits for stability
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    networks:
      - debezium-network

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.6.2
    container_name: ksqldb-server
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8088:8088"   # REST API port 
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_CONNECT_URL: http://debezium-kafka-connect:8083
      KSQL_LISTENERS: http://0.0.0.0:8088
    networks:
      - debezium-network
  kafkacat:
    image: edenhill/kafkacat:1.6.0
    container_name: kafkacat
    depends_on:
      - kafka
    entrypoint: /bin/sh
    tty: true
    networks:
      - debezium-network

volumes:
  pg_data_cdc:
  debezium_plugins:
  debezium_data:
  schema_registry_data:
  esdata:
  kafka-ui-data:

networks:
  debezium-network:
    driver: bridge